apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: dev-serenity
  labels:
    environment: dev
    project: serenity
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "YOUR_GITHUB_USERNAME",
          "password": "YOUR_GITHUB_PAT",
          "auth": "BASE64_ENCODED_USERNAME_COLON_PASSWORD"
        }
      }
    }
